### ISSUE TITLE
OpenSC fails to build with LibreSSL

### ISSUE THREAD

**Issue by h4ckee** [OpenSC/OpenSC#2664]
OpenSC 0.23.0 fails to build with libressl 3.6.0/3.7.0
When configured with **--disable-openssl**, build succeeds.
```
> uname -a
Linux axe.lan 5.10.153 #1 SMP PREEMPT Sat, 12 Nov 2022 12:52:36 +0000 x86_64 GNU/Linux
> lscpu | grep "Model name"
Model name:                      Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
```

```
...
  CC       libopensc_la-card-westcos.lo
In file included from /usr/include/time.h:29,
                 from ../../src/libopensc/cardctl.h:25,
                 from ../../src/libopensc/aux-data.h:30,
                 from ../../src/libopensc/pkcs15.h:29,
                 from asn1.h:29,
                 from card-westcos.c:31:
../../src/libopensc/sc-ossl-compat.h:56:50: error: expected identifier or '(' before 'void'
   56 | #define EVP_PKEY_new_raw_public_key(t, e, p, l) (NULL)
      |                                                  ^~~~
../../src/libopensc/sc-ossl-compat.h:56:50: error: expected ')' before numeric constant
   56 | #define EVP_PKEY_new_raw_public_key(t, e, p, l) (NULL)
      |                                                  ^~~~
In file included from internal.h:45,
                 from card-westcos.c:30:
../../src/libopensc/sc-ossl-compat.h:57:50: error: expected identifier or '(' before numeric constant
   57 | #define EVP_PKEY_get_raw_public_key(p, pu, l)   (0)
      |                                                  ^
make[3]: *** [Makefile:1854: libopensc_la-card-westcos.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/usr/obj/opensc/src/opensc-0.23.0/src/libopensc'
make[2]: *** [Makefile:466: all-recursive] Error 1
make[2]: Leaving directory '/usr/obj/opensc/src/opensc-0.23.0/src'
make[1]: *** [Makefile:610: all-recursive] Error 1
make[1]: Leaving directory '/usr/obj/opensc/src/opensc-0.23.0'
make: *** [Makefile:518: all] Error 2
```

**Comment by dengert** [comment]
I am not familiar with the axe linux distro. What compiler are you using? 

This looks strange, and I don't get the failure when built on Ubuntu 22.04 using libressl-v3.6.1 built from github tag v3.6.1 with OpenSC master built from github using "gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0" 

The lines in sc-ossl-compat.h were introduced by 302ad7047 by  @frankmorgner  They in effect cause `EVP_PKEY_get_raw_public_key` to return NULL and `EVP_PKEY_get_raw_public_key` to return 0. i.e. ignore the routine. These are only called in `p11test_case_common.c` and  `pkcs11-tool.c`. 

It is a complier issue? It looks like any compiler should handle typecase to 0 or NULL.  And the failure is only in the macro which is not used in the failing routine. (It may be flagged as error in all routines with sc-ossl-compat.c)

Can you run the `make` with `-k` to not stop at the first error?

I do get some other errors for routines. Looks like libressl does not support. 
```
../../../src/src/libopensc/card-iasecc.c: In function ‘iasecc_qsign_data_sha1’:
../../../src/src/libopensc/card-iasecc.c:49:36: error: invalid use of incomplete typedef ‘EVP_MD_CTX’ {aka ‘struct env_md_ctx_st’}
   49 | # define  EVP_MD_CTX_md_data(x)  (x->md_data)
      |                                    ^~
../../../src/src/libopensc/card-iasecc.c:3206:19: note: in expansion of macro ‘EVP_MD_CTX_md_data’
 3206 |         md_data = EVP_MD_CTX_md_data(mdctx);
      |                   ^~~~~~~~~~~~~~~~~~
../../../src/src/libopensc/card-iasecc.c: In function ‘iasecc_qsign_data_sha256’:
../../../src/src/libopensc/card-iasecc.c:49:36: error: invalid use of incomplete typedef ‘EVP_MD_CTX’ {aka ‘struct env_md_ctx_st’}
   49 | # define  EVP_MD_CTX_md_data(x)  (x->md_data)
      |                                    ^~
../../../src/src/libopensc/card-iasecc.c:3304:19: note: in expansion of macro ‘EVP_MD_CTX_md_data’
 3304 |         md_data = EVP_MD_CTX_md_data(mdctx);
      |                   ^~~~~~~~~~~~~~~~~~
```
which is a different problem.

**Comment by frankmorgner** [comment]
OK, we can reproduce this and LibreSSL fabulates about some *added* API for `EVP_MD_CTX`, great! :roll_eyes:

**Comment by dengert** [comment]
https://github.com/frankmorgner/OpenSC/commit/d6e3ce91ceea59c22e7ef40f5939e936f9bbc6a0 fixes the bug in  https://github.com/OpenSC/OpenSC/issues/2664#issuecomment-1350244696  but does not address the original problem. 

The original problem appears to be in some differences in OS, configuration, "/var/cache/src/opensc-0.23.0" or some other issue. 

The log https://gist.github.com/h4ckee/57a91f3b51a10c0e51ec5c0316f375d9 shows 9 routines: card-westcos,c, card-authentic.c, card-npa.c pkcs15-oberthur.c, cryptoflex-tool.c, pkcs15-init.c, gids-tool.c, fuzz-pkcs15-crypto.c and fuzz-piv-tool.c fail with:
```
  ../../src/libopensc/sc-ossl-compat.h:56:50: error: expected identifier or '(' before 'void'
   56 | #define EVP_PKEY_new_raw_public_key(t, e, p, l) (NULL)
      |                                                  ^~~~
../../src/libopensc/sc-ossl-compat.h:56:50: error: expected ')' before numeric constant
   56 | #define EVP_PKEY_new_raw_public_key(t, e, p, l) (NULL)
      |                                                  ^~~~
In file included from internal.h:45,
                 from card-westcos.c:30:
../../src/libopensc/sc-ossl-compat.h:57:50: error: expected identifier or '(' before numeric constant
   57 | #define EVP_PKEY_get_raw_public_key(p, pu, l)   (0)
      |                                                  ^                                           
```

**Comment by frankmorgner** [comment]
Not really, it's a syntax error in the header file (which gets included in multiple places). It's not apparent to me what's going on there, so I'd appreciate if @h4ckee could recompile with the changes from #2665

**Comment by frankmorgner** [comment]
I cannot reproduce this problem with a standard build of libressl 3.6.1. Please post the parameter with which your libressl build was created.

**Comment by frankmorgner** [comment]
With 3.7.0 I can reproduce the problem (with 3.6.0 and 3.6.1, however, everything is fine)...

**Comment by frankmorgner** [comment]
I've updated the PR with a fix
