### ISSUE TITLE
Support for 10.8 

### ISSUE THREAD

**Issue by smarek** [OpenSC/OpenSC#146]
Hello,

I'm stuck at problem, gettin ePass2003 to work with 10.8

Steps I tried:
- Installing https://www.opensc-project.org/files/macosx/OpenSC-0.13.0.dmg
  - `opensc-tool -D` not listing epass2003 driver
- Installing opensc package from Homebrew
  - again, although it's 0.13.0 it does not contain epass2003 driver
- Installing pre-built package 0.12.2-10.8.dmg from http://blog.irq0.org/09-16-2012/etokens-slash-smartcards-on-os-x-10-dot-8.html
  - `opensc-tool -D` not listing epass2003, but now it's correct, as support for epass2003 was added ion 0.13.0
- Building OpenSC from git
  - `git clone git://github.com/OpenSC/OpenSC.git
    cd OpenSC
    ./MacOSX/build`
  - As a fix I linked `MacOSX10.8.sdk to /Developer/SDKs/MacOSX10.6.sdk`
  - I've tried to add `--enable-sm --enable-openssh --enable-pcsc` flags
  - fails on building `OpenSC.tokend`
    
    ``````
    OpenSC.tokend/build/security_cdsa_utilities.framework/Headers/handletemplates.h:132:17: error: use 'template' keyword to treat 'findAllRefs' as a dependent template name
    state().findAllRefs<Subtype>(refs);
            ^
            template 
    1 error generated.```
    
    Is there any possible pre-built package for use with 10.8 or step-by-step tutorial for building under new SDKs ?
    
    I've found some possible problems between newest SDK and tokend library, but no tutorial to fix build.
    
    I've installed `libusb 1.0.9` from Homebrew, newest `libccid` installed by tutorial on http://www.gooze.eu/howto/smartcard-quickstarter-guide/installing-libusb-and-upgrading-libccid
    
    I've also installed SmartCardServices v2.0b1 via provided installer: http://smartcardservices.macosforge.org/post/os-x-lion-smartcardservices-installer-v20b1-beta/
    ``````
