### ISSUE TITLE
0.17.0 does not build on Mac OS X 10.6 or earlier

### ISSUE THREAD

**Issue by lbschenkel** [OpenSC/OpenSC#1107]
### Problem Description

I'm the maintainer of the opensc port for MacPorts. I have updated the port to the new 0.17.0 release and I was notified that the build failed in OS X 10.6 and 10.5 due to a missing definition (`SCARD_E_NO_READERS_AVAILABLE`).

Since this did not occur with 0.16.0, and I am not sure if there was a deliberate decision to break compatibility with very old OS X versions or not, I decided to report the build failure here to raise awareness.

### Logs

Full build log from the buildbot is available here (error is at the end):
https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/36763/steps/install-port/logs/stdio

```
reader-pcsc.c: In function ‘pcsc_to_opensc_error’:
reader-pcsc.c:159: error: ‘SCARD_E_NO_READERS_AVAILABLE’ undeclared (first use in this function)
reader-pcsc.c:159: error: (Each undeclared identifier is reported only once
reader-pcsc.c:159: error: for each function it appears in.)
make[3]: *** [libopensc_la-reader-pcsc.lo] Error 1
```

**Comment by lbschenkel** [comment]
On a second thought, I may be wrong on this being a regression. According to
https://github.com/OpenSC/OpenSC/blame/7cff9c28107f360ec4548dfe9ed900538faca157/src/libopensc/reader-pcsc.c
the offending code was committed 9 years ago, so the most likely explanation is that my memory failed me and I encountered this error when building 0.16.0 as well but forgot about it.

**Comment by frankmorgner** [comment]
We decided for 10.7+ on 82624a98b79895e66fbb18dc86af142a4a1ab147, which was already present in 0.15.0. Currently, we are building with 10.10 as minimum requirement. 10.10 was deliberately chosen in da1d4cc78a3f150761c4d636aec98f7698c91687

While fixing the compile error in question may not seem to be very difficult, I wonder if we should. As far as I know, Apple doesn't issue security fixes for anything older than 10.10... I would not want to use my security token with OpenSC on an OS without maintainer support.

**Comment by lbschenkel** [comment]
Thanks. Sorry for the spurious report.

FYI: since I only got notified of build failures in 10.5 and 10.6, this means that the port is actually building on 10.7, 10.8 and 10.9.
