### ISSUE TITLE
opensc-0.18.0.tar.gz package is missing src/ui/invisible_window.h header

### ISSUE THREAD

**Issue by metsma** [OpenSC/OpenSC#1368]
### Problem Description
package is missing src/ui/invisible_window.h header

### Proposed Resolution
Include header in release source package

### Steps to reproduce
Build on windows from opensc-0.18.0.tar.gz package

### Logs
notify.c(70): fatal error C1083: Cannot open include file: 'invisible_window.h': No such file or directory

tar tf opensc-0.18.0.tar.gz |grep ui
opensc-0.18.0/src/ui/
opensc-0.18.0/src/ui/Makefile.am
opensc-0.18.0/src/ui/notify.h
opensc-0.18.0/src/ui/Makefile.mak
opensc-0.18.0/src/ui/wchar_from_char_str.h
opensc-0.18.0/src/ui/strings.c
opensc-0.18.0/src/ui/strings.h
opensc-0.18.0/src/ui/Makefile.in
opensc-0.18.0/src/ui/notify.c

**Comment by frankmorgner** [comment]
use https://github.com/OpenSC/OpenSC/archive/0.18.0.tar.gz as temporary workaround

**Comment by metsma** [comment]
Seems like there is more files missing
exe.manifest : general error c1010070: Failed to load and parse the manifest. The system cannot find the file specified.

**Comment by metsma** [comment]
versioninfo-opensc-notify.rc(8) : error RC2135 : file not found: ..\..\win32\DDORes.dll_14_2302.ico
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x86\rc.EXE"' : return code '0x1'
Stop.

**Comment by frankmorgner** [comment]
I've added them in an other commit.
