### ISSUE TITLE
master - build on Ubuntu 22.04 and Openssl 3.0

### ISSUE THREAD

**Issue by vjardin** [OpenSC/OpenSC#2586]
### Problem Description

Compilation error of git's master with a vanilla Ubuntu 22.04:
```
./configure --enable-openssl
[...]
make
[...]
  CC       opensc_pkcs11_la-framework-pkcs15init.lo
openssl.c: In function ‘sc_pkcs11_register_openssl_mechanisms’:
openssl.c:241:9: error: ‘ENGINE_by_id’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  241 |         e = ENGINE_by_id("gost");
      |         ^
In file included from openssl.c:44:
/usr/include/openssl/engine.h:336:31: note: declared here
  336 | OSSL_DEPRECATEDIN_3_0 ENGINE *ENGINE_by_id(const char *id);
      |                               ^~~~~~~~~~~~
openssl.c:253:17: error: ‘ENGINE_by_id’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  253 |                 e = ENGINE_by_id("dynamic");
      |                 ^
In file included from openssl.c:44:
/usr/include/openssl/engine.h:336:31: note: declared here
  336 | OSSL_DEPRECATEDIN_3_0 ENGINE *ENGINE_by_id(const char *id);
      |                               ^~~~~~~~~~~~
```

**Comment by vjardin** [comment]
As a workaround, we can enforce:
```
export CFLAGS="-Wno-error=deprecated-declarations -Wno-error=maybe-uninitialized" 
```
see https://git.launchpad.net/ubuntu/+source/opensc/tree/debian/rules?h=ubuntu/jammy&id=6e1b1f2014a1a16a87eb5636804f583abaf13245

**Comment by dengert** [comment]
I get the deprecated message using 22.04 too.

OpenSSL has deprecated the use of engines in 3.0 with expectations of providers being used in place of engines. Eventually engines will be dropped. 

OpenSC's only use of engine code is for GOST.  (pkcs11-tool and some other tools can use GOST if available and have OpenSC defines for GOST.) 

So for now there is not much OpenSC can do about GOST. Unless OpenSSL supports GOST or someone produces a OpenSC provider. 

See:
https://github.com/gost-engine/engine/blob/master/README.prov.md

**Comment by vjardinMisc** [comment]
Who does know GHOST code and who can test it ? Should we drop it ?

**Comment by Jakuje** [comment]
I would propose to introduce a configure option to enable the GOST support. I think it is very rarely used by very small group of people and the ENGINE usage with OpenSSL 3.0 will cause many problems to users and distributions with goals to have cleaner build.

**Comment by vjardinMisc** [comment]
But what's about ENGINE_by_id("dynamic") ?

**Comment by Jakuje** [comment]
> But what's about ENGINE_by_id("dynamic") ?

AFAIK that is all part of the block for the loading gost engine, but probably in different openssl configuration or version.

**Comment by dengert** [comment]
Who does know GHOST code and who can test it ? Should we drop it ?

See the list of contributors in https://github.com/gost-engine/engine

We could make optional with OpenSSL-3.0  At least until they convert it to a provider.

**Comment by Jakuje** [comment]
> Who does know GHOST code and who can test it ? Should we drop it ?

Last contribution to GOST code was 5 years back in #997. Previous references were 12 years ago when it was initially introduced and bugfixed in various times.

> See the list of contributors in https://github.com/gost-engine/engine

I know @beldmit, but as far as I know, he does not have the hardware to test this in opensc.

> We could make optional with OpenSSL-3.0 At least until they convert it to a provider.

That would be a reasonable plan.

**Comment by beldmit** [comment]
Russian crypto is implemented in some tokens but I don't have any of them in my disposal just now. They should work as normal PKCS#11 tokens (with some private constants).

I agree with @Jakuje 's proposal to introduce a configure option to enable the GOST support.

**Comment by dengert** [comment]
If the major issue is the use of the loading of the GOST engine in OpenSSL-3.0  then it looks like configuring OpenSC with CPPFLAGS=-DOPENSSL_NO_ENGINE will do it.  This does leave all the OpenSC code and defines for GOST and the card-rutoken.c code still there incase they can convert the engine to a provider in the future. 

See src/pkcs11/openssl.c  where OPENSSL_NO_ENGINE is used in 4 places.

**Comment by beldmit** [comment]
What is the purpose of using GOST engine in OpenSC?

**Comment by dengert** [comment]
Best I can tell is its there for pkcs11-tool. The https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-rutoken.c can still use a token with GOST, as the card driver does not use OpenSSL.

**Comment by vjardinMisc** [comment]
I would feel more comfortable if someone with a deeper inside could submit a related merge request...

**Comment by dengert** [comment]
I can look at that later today.

**Comment by Jakuje** [comment]
This was fixed with #2506 two weeks back.
