### ISSUE TITLE
Can't compile on ubuntu 17.04

### ISSUE THREAD

**Issue by marcu87** [OpenSC/OpenSC#1222]
Hi, 

I'm using ubuntu 17.04, and trying to compile the last version of OpenSC (0.17.0)

So I downloaded the last release, and did:

``` 
./configure
make
```

The `./configure`  gives me no error:

```man support:             no
doc support:             no
thread locking support:  yes
zlib support:            no
readline support:        no
OpenSSL support:         yes
PC/SC support:           yes
CryptoTokenKit support:  no
OpenCT support:          no
CT-API support:          no``
minidriver support:      no
SM support:              yes
SM default module:       libsmm-local.so
DNIe UI support:         no
Debug file:              /tmp/opensc-debug.log
```

and the OpenSSL support is enabled.

The problem comes when I execute `make`, I get the following errors:

```  
CC       libopensc_la-card-sc-hsm.lo
card-sc-hsm.c: In function ‘sc_hsm_perform_chip_authentication’:
card-sc-hsm.c:501:2: warning: implicit declaration of function ‘CRYPTO_add’ [-Wimplicit-function-declaration]
  CRYPTO_add(&ctx->ta_ctx->pub_key->references, 1, CRYPTO_LOCK_EVP_PKEY);
  ^~~~~~~~~~
card-sc-hsm.c:501:34: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
  CRYPTO_add(&ctx->ta_ctx->pub_key->references, 1, CRYPTO_LOCK_EVP_PKEY);
                                  ^~
card-sc-hsm.c:501:51: error: ‘CRYPTO_LOCK_EVP_PKEY’ undeclared (first use in this function)
  CRYPTO_add(&ctx->ta_ctx->pub_key->references, 1, CRYPTO_LOCK_EVP_PKEY);
                                                   ^~~~~~~~~~~~~~~~~~~~
card-sc-hsm.c:501:51: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1532: recipe for target 'libopensc_la-card-sc-hsm.lo' failed
make[3]: *** [libopensc_la-card-sc-hsm.lo] Error 1
make[3]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0/src/libopensc'
Makefile:433: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0/src'
Makefile:556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0'
Makefile:465: recipe for target 'all' failed
make: *** [all] Error 2
```

I guess it's related to `libssl` or something like that, but I'm not sure how to fix it. Does anybody knows how to properly compile on ubuntu 17.04?

Thanks

**Comment by Jakuje** [comment]
Do you have OpenSSL installed? Or is Ubuntu already using LibreSSL out of the box?

**Comment by marcu87** [comment]
@Jakuje yes, I have it.

```
openssl version -a
OpenSSL 1.1.0g  2 Nov 2017
built on: reproducible build, date unspecified
platform: debian-amd64
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\"" 
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
```

**Comment by Jakuje** [comment]
It is probably fixed by the commit 7a39d6d058fb7af1987d38a98860bb065e8a0262 which is already upstream, but missing in the 0.17.0 release. Give it a try with the change in the sc-hsm file:

https://github.com/OpenSC/OpenSC/commit/7a39d6d058fb7af1987d38a98860bb065e8a0262#diff-d41bbe692d0f897375a44b6b3929d83a

it should resolve your problems.

**Comment by marcu87** [comment]
@Jakuje maybe it's related.

So I did modify the file `src/libopensc/card-sc-hsm.c` as you said.

Now, after a `./configure` and `make` I get this error:

```
...
  CC       onepin_opensc_pkcs11_la-slot.lo
  CC       onepin_opensc_pkcs11_la-mechanism.lo
  CC       onepin_opensc_pkcs11_la-openssl.lo
  CC       onepin_opensc_pkcs11_la-framework-pkcs15.lo
  CC       onepin_opensc_pkcs11_la-framework-pkcs15init.lo
  CC       onepin_opensc_pkcs11_la-debug.lo
  CC       onepin_opensc_pkcs11_la-pkcs11-display.lo
  CCLD     onepin-opensc-pkcs11.la
make[3]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0/src/pkcs11'
Making all in tools
make[3]: Entering directory '/home/myUser/Programs/opensc/opensc-0.17.0/src/tools'
  CC       opensc-tool.o
  CC       util.o
  CCLD     opensc-tool
../../src/libopensc/.libs/libopensc.so: undefined reference to `M_ASN1_OCTET_STRING_set'
collect2: error: ld returned 1 exit status
Makefile:773: recipe for target 'opensc-tool' failed
make[3]: *** [opensc-tool] Error 1
make[3]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0/src/tools'
Makefile:433: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0/src'
Makefile:556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/myUser/Programs/opensc/opensc-0.17.0'
Makefile:465: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Jakuje** [comment]
The best would be to try with master. But if you apply the other changes from that commit (`src/sm/sm-eac.c`, `src/tools/npa-tool.c), it should be resolved too.

**Comment by marcu87** [comment]
@Jakuje now it compiles witouth errors, but when I execute `pkcs11-tool` I got this error:

```
pkcs11-tool: error while loading shared libraries: libopensc.so.5: cannot open shared object file: No such file or directory
```

Maybe I'm gonna try to install from master. 
But cloning the project and then doing a `./configure` doesn't work. What are the steps to install after a clone?

**Comment by Jakuje** [comment]
You need to run `./bootstrap` before running `./configure`.

How did you start `pkcs11-tool`?

**Comment by marcu87** [comment]
I did execute this command: `pkcs11-tool -t -l`

Got it from https://github.com/OpenSC/OpenSC/issues/810

It worked with my previous version of  OpenSC (0.16)

**Comment by marcu87** [comment]
Same problem installing it from master.

**Comment by Jakuje** [comment]
It looks like you installed the libraries to different path than is expected by your system.

The easiest would be to run the `pkcs11-tool` directly from the build directory, instead. Such as

    ./src/tools/pkcs11-tool

If you want to run it from installed path, you need to adjust `--libdir` and `--prefix` arguments to `configure`.

**Comment by marcu87** [comment]
Thanks :1st_place_medal:@Jakuje!! That fixed my problem!
