### ISSUE TITLE
`test-duplicate-symbols.sh` incorrectly calculates duplicates

### ISSUE THREAD

**Issue by H5117** [OpenSC/OpenSC#3298]
```
$ cat ../test.exports 
sc_transmit_apdu
sc_unlock
$ ./test-duplicate-symbols.sh 
$ echo $?
0
$ echo "sc_unlock" >> ../test.exports 
$ ./test-duplicate-symbols.sh 
$ echo $?
0
$ echo "sc_transmit_apdu" >> ../test.exports 
$ ./test-duplicate-symbols.sh 
There are 1 duplicate symbols in '../test.exports': sc_transmit_apdu
sc_unlock
There are duplicate symbols
$ echo $?
1
```

**Comment by Jakuje** [comment]
Good catch! Seems like the detection in 

https://github.com/OpenSC/OpenSC/blob/9cb58e648d100c1ef068c4afe52114b288ebcff1/tests/test-duplicate-symbols.sh#L8

is correct.

But the problem is in 
https://github.com/OpenSC/OpenSC/blob/9cb58e648d100c1ef068c4afe52114b288ebcff1/tests/test-duplicate-symbols.sh#L9

I added the `-n` to avoid returning one line when there was no match, but missed this corner case when there is one duplicate symbol.

Seems like this worked initially ok, until I broke it with d5dea2dd1b3a412adace25ee8a9ff2e73a97508a. Should be fixed with #3300.
