### ISSUE TITLE
Derive secret with ECC

### ISSUE THREAD

**Issue by Ovomaltine85** [OpenSC/OpenSC#898]
I generated a new keypair on HSM (softhsm2) with the following code:

`pkcs11-tool --module /usr/local/lib/softhsm/libsofthsm2.so -l --pin 1234 --slot 1 --keypairgen --key-type EC:secp384r1 --id 1111 --label testtoken`

With this private key stored on the hsm I want to derive a shared secret with another pubkey. Therefor I converted the public key from a x509 with openssl ec to DER format.

When I use the created pubkey.der to derive a shared secret I get the following error.
`pkcs11-tool --module /usr/local/lib/softhsm/libsofthsm2.so --slot 1 -l --pin 1234 --id 1111 --derive --input-file pubkey.der -m ECDH1-DERIVE --output-file shared`

Error:
`Using derive algorithm 0x00001050 ECDH1-DERIVE
error: PKCS11 function C_DeriveKey failed: rv = CKR_TEMPLATE_INCOMPLETE (0xd0)
Aborting.`

ECDH1-DERIVE is a valid supported mechanism by the HSM.

Why is the CKR Template incomplete and how can I solve this problem to derive a shared secret?

Regards

**Comment by dengert** [comment]
pkcs11-tool.c in routine derive_ec_key builds the newkey_template with:
CKA_TOKEN=FALSE  (Session only)
CKA_CLASS=CKO_SECRET_KEY
CKA_KEY_TYPE=CKK_GENERIC_SECRET
CKA_ENCRYPT=TRUE
CKA_DECRYPT=TRUE

Examples from PKCS\#11 2.20 in section 11.14  and PKCS\#11 2.40 under C_Derive would indicate that above has all the required attributes in the template. 

The problem might be coming  from SoftHSM.cpp:

 8866                 case CKK_GENERIC_SECRET:
 8867                         if (byteLen == 0)
 8868                         {
 8869                                 INFO_MSG("CKA_VALUE_LEN must be set");
 8870                                 return CKR_TEMPLATE_INCONSISTENT;
 8871                         }

I don't see any PKCS\#11 requirement that during a derive for a  CKK_GENERIC_SECRET the length must be supplied. In particular, the size if the  CKK_GENERIC_SECRET is based on the key size use to derive it.

After the key is derived, the calling application can then use PKCS#11 calls to use the key, or extract it, if its is extractable.

 I think this is a SoftHSM issue, not a OpenSC pkcs11-tool issue. 

I don't use SoftHSM2. If you can debug it it would help to locate where the  CKR_TEMPLATE_INCONSISTENT is being set. There are 70 places where it could be set.

**Comment by Ovomaltine85** [comment]
Thank you for your help. Just for notice. The error message is not CKR_TEMPLATE_INCOSISTENT but CKR_TEMPLATE_INCOMPLETE.

I will also give this issue to the softhsm forum.

**Comment by dengert** [comment]
Sorry, But it could still be the CKA_VALUE_LEN:
 
6312         // CKA_VALUE_LEN must be specified
 6313         if (keyLen == 0)
 6314         {
 6315                 INFO_MSG("Missing CKA_VALUE_LEN in pTemplate");
 6316                 return CKR_TEMPLATE_INCOMPLETE;
 6317         }


PKCS\#11 v2.40 (pkcs110curr-v2.40-cs01.pdf) has:

2.3.9 Elliptic curve Diffie-Hellman key derivation
"This mechanism derives a secret value, and truncates the result according to the CKA_KEY_TYPE
attribute of the template and, **if it has one and the key type supports** it, the CKA_VALUE_LEN attribute of
the template. (The truncation removes bytes from the leading end of the secret value.) The mechanism
contributes the result as the CKA_VALUE attribute of the new key; other attributes required by the key
type must be specified in the template."

This implies  CKA_VALUE_LEN is optional. 

For a hardware token, (which softhsm is not), the value of the secretkey and its length may reside on the token, and its length and value may not be extractable.
If it is extractable, a call(s) to C_GetAttributeValue to get the length and value can be made and any truncation can be done.

**Comment by Ovomaltine85** [comment]
Thank you, so this means I cannot do anything and have to wait until the issue with softhsm is fixed?

**Comment by dengert** [comment]
I think so. I have an untested patch to https://github.com/opendnssec/SoftHSMv2 develop branch if you are willing to try it. There were number of changes in this area between version 2.0.0 and develop dealing with truncating the results that were fixed. 

You could also hack the SoftHSMv2  src/lib/tests/DeriveTests.cpp 

Or hack the OpenSC pkcs11-tool.c to add CKA_VALUE_LEN to the template. But you have to know what size it will return based on the curve.

**Comment by Ovomaltine85** [comment]
I already installed the current version 2.2.0rc1 of softhsm2, but this didn't made a difference to the problem.
Unfortunately I'm not so experienced with the programming of PKCS#11 in C so its quite hard for me to find out at which places I have to edit something. 

A different approach to solve this problem was to use openssl pkeyutl. But coincidentally there is also a bug in the current version that doesn't let you access the token via pkcs11 engine to derive a shared secret :-/

I would appreciate any further help!

**Comment by dengert** [comment]
The  problem with pkeyutl calling the engine via libp11 may have the same problem of not passing CKA_VALUE_LEN. 

I will submit later today or this week a patch to softhsm to make  CKA_VALUE_LEN optional or if 0 to mean let the PKCS\#11 determine the length. It should apply to 2.2.0rc1 

OpenSC PKCS\#11 only supports  deriving a CKK_GENERIC_SECRET. I will also look at allowing other keys types to be derived, which in the case of AES CKA_VALUE_LEN specifies the size of the key. 

pkcs11-tool will then need some changes to allow on to specify for teh derived key its type and optionally it size. 

The above will take a few days.

**Comment by mouse07410** [comment]
> A different approach to solve this problem was to use openssl pkeyutl. But coincidentally there is also a bug in the current version that doesn't let you access the token via pkcs11 engine to derive a shared secret :-/

Hmm, what do you make of this:
```
openssl pkeyutl -engine pkcs11 -keyform engine -derive -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;type=private" -peerform DER -peerkey /tmp/derive.76254.pub.der -hexdump
engine "pkcs11" set.
PKCS#11 token PIN: 
0000 - 3f 2e c4 6c 6a 14 da 0f-31 9d 69 6e 92 d2 5c cf   ?..lj...1.in..\.
0010 - 7f 7a 3b 76 d7 4d 5c 98-98 86 b3 d5 aa 8b 80 48   .z;v.M\........H
```

I think the problem is with SoftHSMv2.

**Comment by Ovomaltine85** [comment]
Thank you dengert, I'm quite excited to that fix.

`openssl pkeyutl -engine pkcs11 -keyform engine -derive -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;type=private" -peerform DER -peerkey /tmp/derive.76254.pub.der -hexdump`
Produced an error of incompatibility. Currently I cannot reproduce this error because I made some updates/downgrades of openssl and libp11 versions for testing purpose. The result of this is that I now have a segmentation fault when I execute this command :-D

But before I tried to use dgst instead of pkeyutl, something like:
`openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:...." -sha384 -out text.sig < text.txt`
This was working correctly and produced no error. So could it still be the problem of SoftHSM2?

**Comment by mouse07410** [comment]
> [...] `openssl pkeyutl` Produced an error of incompatibility...

Observe: on my device (a real physical PIV token) `pkeyutl` consistently worked and derived keys fine. On your device (SoftHSMv2) it failed and produced an error. Where do you think the problem cause is likely to be? 

SoftHSMv2 seems to need a fix. If I understand correctly, @dengert concurs, and offered a PR to SoftHSMv2 that takes care of this.

**Comment by Ovomaltine85** [comment]
I believe you. The suprising fact was that openssl dgst is working to sign with the SoftHSM token. But thats another function. I'll wait for the fix by dengert.

Another question: After trying out different versions of openssl and lib11 I discover now segmentation faults when I access the HSM token via the pkcs11 engine in openssl commands.
Can you give a hint what could be the reason for that?

**Comment by dengert** [comment]
You are mixing apples and oranges. ECC has two methods ECDSA for signature and ECDH derive to get a symmetric key to use for encryption and decryption. You can not encrypt with ECC, unlike RSA where you can.

The proposed fix for softhsm is for ECDH derive. 

The second is for pkcs11-tool to allow one to derive an CKK_AES or CKK_DESx symmetric key rather then just a  CKK_GENERIC_SECRET, so it can use softhsm and write the key out in OpenSSL format. 

The third is to support in OpenSC the ability to derive a  CKK_AES or CKK_DESx too.

**Comment by dengert** [comment]
@mouse07410 in response to https://github.com/OpenSC/OpenSC/issues/898#issuecomment-258686804 OpenSSL engine in libp11 that is calling p11-kit that is calling opensc-pkcs11.so. 

@Ovomaltine85  in https://github.com/OpenSC/OpenSC/issues/898#issuecomment-258690170 tried using `pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;type=private` But this only works for opensc-pkcs11.so with a PIV card.

**Comment by dengert** [comment]
@Ovomaltine85  Please have a look at this PR.  https://github.com/OpenSC/OpenSC/pull/901
It can work with unmodified SoftHSM, if you add the --derive-pass-der option. 
It is not the full set of changes I would eventually like to see, but should get around you problems.

**Comment by Ovomaltine85** [comment]
Thank you for your great work. I wanted to try out your adjustments and to rebuild OpenSC.

But from now everytime I want to build it I get the following error:
`../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_CIPHER_CTX_init'
../../src/libopensc/.libs/libopensc.so: undefined reference to `RSA_PKCS1_SSLeay'
../../src/libopensc/.libs/libopensc.so: undefined reference to `ERR_free_strings'
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_MD_CTX_cleanup'
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_CIPHER_CTX_cleanup'
../../src/libopensc/.libs/libopensc.so: undefined reference to `i2c_ASN1_INTEGER'
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_MD_CTX_init'
../../src/libopensc/.libs/libopensc.so: undefined reference to `ERR_load_crypto_strings'
`
What is the reason for that? It appeared the first time. I think it has to do with all the changes and adjustments to OpenSSL.

**Comment by dengert** [comment]
Where are you getting these messages?
How did you apply the changes?
After downloading the clone or change, you need to run the ./bootstrap script first
Then you can do configure, make, install.

What OS are you using?
What configure options are you using? 

It looks like you are mixing some older version of OpenSSL with a newer version of pkcs11-tool.c.


Are using using git?

The ECDH requires OpenSSL-1.0.2 or 1.1.0.  Are you mixing up versions?
The change is on top of the github.com OpenSC master.

**Comment by Ovomaltine85** [comment]
I get those messages when I call make after configuring the installation.

Currently I have installed two versions of OpenSSL:
/usr/local/bin/openssl --> 1.0.2j
/usr/bin/openssl --> 1.0.1t

I tried the current OpenSC-master and OpenSC 0.16. as well. Both installations with and without your recently edited pkcs11-tool.c. I downloaded a raw copy of your new pkcs11-tool.c and copied it before configuring to opensc/src/tools/. The error also occurs if I download the current release of OpenSC 0.16 and didn't make a change to pkcs11-tool.c

When I'm installation I use the following commands:

./bootstrap
./configure

after configuring library env variables are set to:
OPENSSL_CFLAGS:          -I/usr/local/include 
OPENSSL_LIBS:            -L/usr/local/lib -lcrypto

This should be correct I think because those libraries should point to the OpenSSL 1.0.2j installation.

After this I run make && make install and there is the error thrown:
`make[3]: Entering directory '/home/thomas/Downloads/opensc-0.16.0/src/tools'
  CC       opensc-tool.o
  CC       util.o
  CCLD     opensc-tool
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_CIPHER_CTX_init'
../../src/libopensc/.libs/libopensc.so: undefined reference to `RSA_PKCS1_SSLeay'
../../src/libopensc/.libs/libopensc.so: undefined reference to `ERR_free_strings'
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_MD_CTX_cleanup'
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_CIPHER_CTX_cleanup'
../../src/libopensc/.libs/libopensc.so: undefined reference to `i2c_ASN1_INTEGER'
../../src/libopensc/.libs/libopensc.so: undefined reference to `EVP_MD_CTX_init'
../../src/libopensc/.libs/libopensc.so: undefined reference to `ERR_load_crypto_strings'
collect2: error: ld returned 1 exit status
Makefile:666: recipe for target 'opensc-tool' failed
make[3]: *** [opensc-tool] Error 1
make[3]: Leaving directory '/home/thomas/Downloads/opensc-0.16.0/src/tools'
Makefile:410: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/thomas/Downloads/opensc-0.16.0/src'
Makefile:538: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/thomas/Downloads/opensc-0.16.0'
Makefile:444: recipe for target 'all' failed
make: *** [all] Error 2
`

I run a Debian GNU/Linux 8.5 (jessie). 
A few days ago I already reinstalled OpenSC and everything went fine. I also think that is to do with OpenSSL but cannot reproduce where exactly the error is.

**Comment by dengert** [comment]
If you are using an alternate location for OpenSSL, you need to set them BEFORE configure. Use
 `configure --help` to see what the choices are. 

You can use the ldd command on each executable and library to see what libraries it will try and load. 
The  pkcs\#11 modules are dynamically loaded and may be loading from a different location. 

You could also try setting in environment export LD_LIBRARY_PATH=path to libs before running. 

To allow me to build OpenSC with multiple OpenSSL versions, I have a set of directories 
/opt/ossl-X where X  is 0.9.7, 0.9.8, 1.0.1, 1.0.2 and 1.1 so I can build 5 versions.

So when configuring OpenSC for OpenSSL-1.0.2 I do:
CC=gcc
CFLAGS=-g -Werror
CPPFLAGS=-DDEBUG
LDFLAGS=-g -Wl,-rpath,/opt/ossl-1.0.2/lib
export CC CFLAGS CPPFLAGS LDFLAGS 

OPENSSL_CFLAGS=-I/opt/ossl-1.0.2/include
OPENSSL_LIBS=-L/opt/ossl-1.0.2/lib -lcrypto
export OPENSSL_LIBS OPENSSL_CFLAGS

PKG_CONFIG_PATH=/opt/ossl-1.0.2/lib/pkgconfig
export PKG_CONFIG_PATH

../src/configure --disable-silent-rules --prefix=/opt/ossl-1.0.2 --enable-pcsc --with-pcsc-provider=/usr/lib/libpcsclite.so --disable-doc
The above is run is a directory for each version of OpenSC I want to build
from the OPenSC source directory:
cd ../opensc-build-X (one for each ossl)
then the the make
then the make install with install into --prefix, i.e. /opt/ossl-X 

The LDFLAGS=-g -Wl,-rpath,/opt/ossl-1.0.2/lib tells the linker to add -rpath /opt/ossl-1.0.2/lib to each library and module. 
(the -g above and -g in the CFLAGS make gdb debugging easy.)

**Comment by Ovomaltine85** [comment]
At first the good news:
**It works very fine now with the --derive-pass-der option. You did a great job!**
As I understand you implemented currently some fixes to pkcs11-tool.c. What do you think when those adjustments will get _regular_ part of OpenSC releases? Do you think it will substitutes the already existing --derive option?

But I still faced some errors during the building-process of OpenSC. I considered your hints and I succeeded in building the current master copy of OpenSC, but curiously not with opensc-0.16 from the release section.
Before that I built and installed a new OpenSSL version under /opt/openssl-1.1.0 and set all the paths to that. As I said, with OpenSC-master it works well, with the package from the current release section not.

The last one produces errors during building process like that:
`pkcs15-lib.c:2185:6: error: dereferencing pointer to incomplete type
   rsa->n = BN_bin2bn(key->modulus.data, key->modulus.len, NULL);
      ^
pkcs15-lib.c:2186:6: error: dereferencing pointer to incomplete type
   rsa->e = BN_bin2bn(key->exponent.data, key->exponent.len, NULL);
      ^
pkcs15-lib.c:2187:6: error: dereferencing pointer to incomplete type
   rsa->d = BN_bin2bn(key->d.data, key->d.len, NULL);
      ^
pkcs15-lib.c:2188:6: error: dereferencing pointer to incomplete type
   rsa->p = BN_bin2bn(key->p.data, key->p.len, NULL);
      ^
pkcs15-lib.c:2189:6: error: dereferencing pointer to incomplete type
   rsa->q = BN_bin2bn(key->q.data, key->q.len, NULL);
      ^
pkcs15-lib.c:2190:11: error: dereferencing pointer to incomplete type
   if (!rsa->dmp1)
           ^
pkcs15-lib.c:2191:7: error: dereferencing pointer to incomplete type
    rsa->dmp1 = BN_new();
       ^
pkcs15-lib.c:2192:11: error: dereferencing pointer to incomplete type
   if (!rsa->dmq1)
           ^
pkcs15-lib.c:2193:7: error: dereferencing pointer to incomplete type
    rsa->dmq1 = BN_new();
       ^
pkcs15-lib.c:2194:11: error: dereferencing pointer to incomplete type
   if (!rsa->iqmp)
           ^
pkcs15-lib.c:2195:7: error: dereferencing pointer to incomplete type
    rsa->iqmp = BN_new();
       ^
pkcs15-lib.c:2200:18: error: dereferencing pointer to incomplete type
   BN_sub(aux, rsa->q, BN_value_one());
                  ^
In file included from pkcs15-lib.c:49:0:
pkcs15-lib.c:2201:13: error: dereferencing pointer to incomplete type
   BN_mod(rsa->dmq1, rsa->d, aux, bn_ctx);
`
But this is not so prioritised at the moment. Its more important that the derivation is working

**Comment by dengert** [comment]
Add a comment to #901 stating it works as you requested. That will get in committed soon. 
OpenSC 0.16 will not work with OpenSSL-1.1.0. OpenSSL made **MAJOR** changes to the API with 1.1.0. 
Your error messages are due to the OpenSSL changes to the API. 

OpenSC added comparability code with https://github.com/OpenSC/OpenSC/commit/5fb4db63739915399ed9f0d4499b79a1cc9e0139
and some other fixes since. These are in the master branch. 

I do not know when a new version will be released.

**Comment by frankmorgner** [comment]
Closing this issue due to inactivity. Please re-open the ticket if more input is available.
